services:
  zephyr:
    image: monder87/my-zephyr-dev-env:2.0.4
    container_name: zephyr-dev
    privileged: true
    volumes:
      - ~/Docker/Work/zephyrproject:/workdir
      - ~/STMicroelectronics/STM32Cube/STM32CubeProgrammer:/root/STMicroelectronics/STM32Cube/STM32CubeProgrammer
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - UDEV=1
    ports:
      - "5900:5900" # <--- exposes VNC port to localhost:5900
    stdin_open: true
    tty: true
